language: python
# command to install dependencies
install: "pip install nosegae"
# command to run tests
before_script:
- wget https://googleappengine.googlecode.com/files/google_appengine_1.8.9.zip -nv
- unzip -q google_appengine_1.8.9.zip
script: nosetests --with-gae server/attender-mobile/tests